// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH1bAFO2qP_u60pLh35OiBsXDMrcuJgYE',
    appId: '1:46171882567:web:567c81b20352fb4e871d62',
    messagingSenderId: '46171882567',
    projectId: 'chatzenify',
    authDomain: 'chatzenify.firebaseapp.com',
    storageBucket: 'chatzenify.firebasestorage.app',
    measurementId: 'G-QPJL74ZWVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPDp_eHjSI0Z9YfN7QX61FRyH1zgh3m1w',
    appId: '1:46171882567:android:db54cd819563a035871d62',
    messagingSenderId: '46171882567',
    projectId: 'chatzenify',
    storageBucket: 'chatzenify.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7oxQRCahhuLy8u_pDFApFZiiUA2UIgrc',
    appId: '1:46171882567:ios:8140afbb8de2579e871d62',
    messagingSenderId: '46171882567',
    projectId: 'chatzenify',
    storageBucket: 'chatzenify.firebasestorage.app',
    iosBundleId: 'com.example.zenifytripGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7oxQRCahhuLy8u_pDFApFZiiUA2UIgrc',
    appId: '1:46171882567:ios:8140afbb8de2579e871d62',
    messagingSenderId: '46171882567',
    projectId: 'chatzenify',
    storageBucket: 'chatzenify.firebasestorage.app',
    iosBundleId: 'com.example.zenifytripGuide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH1bAFO2qP_u60pLh35OiBsXDMrcuJgYE',
    appId: '1:46171882567:web:6233d8427fc3a323871d62',
    messagingSenderId: '46171882567',
    projectId: 'chatzenify',
    authDomain: 'chatzenify.firebaseapp.com',
    storageBucket: 'chatzenify.firebasestorage.app',
    measurementId: 'G-6VT2QTFGHX',
  );
}
